import type { NextPage } from 'next'
import Head from 'next/head'
import CartItem from '../components/CartItem'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trending Product
        </h1>
        <div className={styles.list__product}>
          <CartItem />
          <CartItem />
          <CartItem />
          <CartItem />
        </div>

      </main>
    </div>
  )
}

export default Home
