import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Products from './products'
import { ProductServices, fetchProductByLimit } from '../services/productServices.js'

export async function getServerSideProps(productsPerPage) {
  const res = await ProductServices();
  return {
    props: {
      products: res.data,
    },
  }
}
const Home = (props) => {
  // const [productsPerPage] = useState(5);
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trending Product
        </h1>
        <div className={styles.list__product}>
          <Products products={props.products} />
        </div>

      </main>
    </div>
  )
}


export default Home
